import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./context/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#dae2fd",
        "secondary-fixed-dim": "#4edea3",
        "on-error": "#690005",
        "on-tertiary-container": "#3e2400",
        "on-surface": "#dae2fd",
        "on-secondary-fixed": "#002113",
        "on-primary": "#002e6a",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary-container": "#ca8100",
        "primary-container": "#4d8eff",
        "on-surface-variant": "#c2c6d6",
        "inverse-surface": "#dae2fd",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed": "#ffddb8",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "on-primary-container": "#00285d",
        "surface-bright": "#31394d",
        "surface-container": "#171f33",
        "surface-tint": "#adc6ff",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-high": "#222a3d",
        "outline-variant": "#424754",
        "on-primary-fixed": "#001a42",
        "on-secondary-container": "#00311f",
        "error-container": "#93000a",
        secondary: "#4edea3",
        tertiary: "#ffb95f",
        error: "#ffb4ab",
        "on-primary-fixed-variant": "#004395",
        "surface-dim": "#0b1326",
        "on-tertiary": "#472a00",
        outline: "#8c909f",
        "primary-fixed-dim": "#adc6ff",
        "secondary-container": "#00a572",
        "on-secondary": "#003824",
        "tertiary-fixed-dim": "#ffb95f",
        surface: "#0b1326",
        "surface-variant": "#2d3449",
        primary: "#adc6ff",
        "surface-container-highest": "#2d3449",
        "inverse-primary": "#005ac2",
        "on-tertiary-fixed": "#2a1700",
        "secondary-fixed": "#6ffbbe",
        background: "#0b1326",
        "inverse-on-surface": "#283044",
      },
      borderRadius: {
        DEFAULT: "1rem",
        sm: "0.5rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "stack-gap": "1rem",
        "container-margin": "1.25rem",
        "element-padding": "1rem",
        "section-gap": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      keyframes: {
        "gradient-xy": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        "drawLine": {
          to: { strokeDashoffset: "0" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 15px rgba(173, 198, 255, 0.3)" },
          "50%": { boxShadow: "0 0 30px rgba(173, 198, 255, 0.6)" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "gradient-xy": "gradient-xy 15s ease infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "fade-in-up": "fade-in-up 0.4s ease-out forwards",
      },
    },
  },
  plugins: [],
};

export default config;
